MACHINE StringTypeError
PROPERTIES
1234567
=
"12345"
END

/*

parser_version('2016-04-26 11:10:24.146').
classical_b('StringTypeError',['/Users/leuschel/git_root/prob_examples/public_examples/B/ErrorMachines/StringTypeError.mch']).
machine(abstract_machine(pos(1,1,1,1,6,3),machine(pos(2,1,1,1,1,7)),machine_header(pos(3,1,1,9,1,23),'StringTypeError',[]),[properties(pos(4,1,2,1,5,5),
equal(pos(5,1,3,1,5,5),
integer(pos(6,1,3,1,3,7),1234567),
string(pos(7,1,5,1,5,5),'12345')))])).

*/