
MACHINE ManyPartialFunctions
/* needs DEFAULT_SETSIZE of 5 or larger */
SETS /* deferred */
  aa2;
  aa3;
  aa4;
  aa5;
  aa6;
  aa7;
  aa8;
  aa9;
  aa10;
  aa11;
  aa12;
  aa13;
  aa14;
  aa15;
  aa16;
  aa17;
  aa18;
  aa19;
  aa20;
  aa21;
  aa22;
  aa23;
  aa24;
  aa25
CONCRETE_CONSTANTS
  aa26,
  aa27,
  aa28,
  aa29,
  aa30,
  aa31,
  aa32,
  aa33,
  aa34,
  aa35,
  aa36,
  aa37,
  aa38,
  aa39,
  aa40,
  aa41,
  aa42,
  aa43,
  aa44,
  aa45,
  aa46,
  aa47,
  aa48,
  aa49,
  aa50,
  aa51,
  aa52,
  aa53,
  aa54,
  aa55,
  aa56,
  aa57,
  aa58,
  aa59,
  aa60,
  aa61,
  aa62,
  aa63,
  aa64,
  aa65,
  aa66,
  aa67,
  aa68,
  aa69,
  aa70,
  aa71,
  aa72,
  aa73,
  aa74,
  aa75,
  aa76,
  aa77,
  aa78,
  aa79,
  aa80,
  aa81,
  aa82,
  aa83,
  aa84,
  aa85,
  aa86,
  aa87,
  aa88,
  aa89,
  aa90,
  aa91,
  aa92,
  aa93,
  aa94,
  aa95,
  aa96,
  aa97,
  aa98,
  aa99,
  aa100,
  aa101,
  aa102,
  aa103,
  aa104,
  aa105,
  aa106,
  aa107,
  aa108,
  aa109,
  aa110,
  aa111,
  aa112,
  aa113,
  aa114,
  aa115,
  aa116,
  aa117,
  aa118,
  aa119,
  aa120,
  aa121,
  aa122,
  aa123,
  aa124,
  aa125,
  aa126,
  aa127,
  aa128,
  aa129,
  aa130,
  aa131,
  aa132,
  aa133,
  aa134,
  aa135,
  aa136,
  aa137,
  aa138,
  aa139,
  aa140,
  aa141,
  aa142,
  aa143,
  aa144,
  aa145,
  aa146,
  aa147,
  aa148,
  aa149,
  aa150,
  aa151,
  aa152,
  aa153,
  aa154,
  aa155,
  aa156,
  aa157,
  aa158,
  aa159,
  aa160,
  aa161,
  aa162,
  aa163,
  aa164,
  aa165,
  aa166,
  aa167,
  aa168,
  aa169,
  aa170,
  aa171,
  aa172,
  aa173,
  aa174,
  aa175,
  aa176,
  aa177,
  aa178,
  aa179,
  aa180,
  aa181,
  aa182,
  aa183,
  aa184,
  aa185,
  aa186,
  aa187,
  aa188,
  aa189,
  aa190,
  aa191,
  aa192,
  aa193,
  aa194,
  aa195,
  aa196,
  aa197,
  aa198,
  aa199,
  aa200,
  aa201,
  aa0,
  aa202,
  aa203,
  aa204,
  aa205,
  aa206,
  aa207,
  aa208,
  aa209,
  aa210,
  aa211,
  aa212,
  aa213,
  aa214,
  aa215,
  aa216,
  aa217,
  aa218,
  aa219,
  aa220,
  aa221,
  aa222,
  aa223,
  aa224,
  aa225,
  aa226,
  aa227,
  aa228,
  aa229,
  aa230,
  aa231,
  aa232,
  aa233,
  aa234,
  aa235,
  aa236,
  aa237,
  aa1,
  aa238,
  aa239,
  aa240,
  aa241,
  aa242,
  aa243,
  aa244,
  aa245,
  aa246,
  aa247,
  aa248,
  aa249,
  aa250,
  aa251,
  aa252,
  aa253,
  aa254,
  aa255,
  aa256,
  aa257,
  aa258,
  aa259,
  aa260,
  aa261,
  aa262,
  aa263,
  aa264,
  aa265,
  aa266,
  aa267,
  aa268,
  aa269,
  aa270,
  aa271,
  aa272,
  aa273,
  aa274,
  aa275,
  aa276,
  aa277,
  aa278,
  aa279,
  aa280,
  aa281,
  aa282,
  aa283,
  aa284,
  aa285,
  aa286,
  aa287,
  aa288,
  aa289,
  aa290,
  aa291,
  aa292,
  aa293,
  aa294,
  aa295,
  aa296,
  aa297,
  aa298,
  aa299,
  aa300,
  aa301,
  aa302,
  aa303,
  aa304,
  aa305,
  aa306,
  aa307,
  aa308,
  aa309,
  aa310,
  aa311,
  aa312,
  aa313,
  aa314,
  aa315,
  aa316,
  aa317,
  aa318,
  aa319,
  aa320,
  aa321,
  aa322,
  aa323,
  aa324,
  aa325,
  aa326,
  aa327,
  aa328,
  aa329,
  aa330,
  aa331,
  aa332,
  aa333,
  aa334,
  aa335,
  aa336
PROPERTIES
    aa26 : INTEGER
  & aa27 : INTEGER
  & aa28 : INTEGER
  & aa29 : INTEGER
  & aa30 : INTEGER
  & aa31 : INTEGER
  & aa32 : INTEGER
  & aa33 : INTEGER
  & aa34 : INTEGER
  & aa35 : INTEGER
  & aa36 : INTEGER
  & aa37 : INTEGER
  & aa38 : INTEGER
  & aa39 : INTEGER
  & aa40 : INTEGER
  & aa41 : INTEGER
  & aa42 : INTEGER
  & aa43 : INTEGER
  & aa44 : INTEGER
  & aa45 : INTEGER
  & aa46 : INTEGER
  & aa47 : INTEGER
  & aa48 : INTEGER
  & aa49 : INTEGER
  & aa50 : INTEGER
  & aa51 : INTEGER
  & aa52 : INTEGER
  & aa53 : INTEGER
  & aa54 : INTEGER
  & aa55 : INTEGER
  & aa56 : INTEGER
  & aa57 : INTEGER
  & aa58 : INTEGER
  & aa59 : INTEGER
  & aa60 : INTEGER
  & aa61 : INTEGER
  & aa62 : INTEGER
  & aa63 : INTEGER
  & aa64 : INTEGER
  & aa65 : INTEGER
  & aa66 : INTEGER
  & aa67 : INTEGER
  & aa68 : INTEGER
  & aa69 : INTEGER
  & aa70 : INTEGER
  & aa71 : INTEGER
  & aa72 : INTEGER
  & aa73 : INTEGER
  & aa74 : INTEGER
  & aa75 : INTEGER
  & aa76 : INTEGER
  & aa77 : INTEGER
  & aa78 : INTEGER
  & aa79 : INTEGER
  & aa80 : INTEGER
  & aa81 : INTEGER
  & aa82 : INTEGER
  & aa83 : INTEGER
  & aa84 : INTEGER
  & aa85 : INTEGER
  & aa86 : INTEGER
  & aa87 : INTEGER
  & aa88 : INTEGER
  & aa89 : INTEGER
  & aa90 : INTEGER
  & aa91 : INTEGER
  & aa92 : INTEGER
  & aa93 : POW(INTEGER)
  & aa94 : POW(INTEGER)
  & aa95 : POW(INTEGER)
  & aa96 : POW(INTEGER)
  & aa97 : POW(INTEGER)
  & aa98 : POW(INTEGER)
  & aa99 : POW(INTEGER)
  & aa100 : POW(INTEGER)
  & aa101 : POW(INTEGER)
  & aa102 : POW(INTEGER)
  & aa103 : INTEGER
  & aa104 : POW(INTEGER)
  & aa105 : POW(INTEGER)
  & aa106 : POW(INTEGER)
  & aa107 : POW(INTEGER)
  & aa108 : POW(INTEGER)
  & aa109 : POW(INTEGER)
  & aa110 : POW(INTEGER)
  & aa111 : POW(INTEGER)
  & aa112 : POW(INTEGER)
  & aa113 : POW(INTEGER)
  & aa114 : POW(INTEGER)
  & aa115 : POW(aa2)
  & aa116 : POW(aa2)
  & aa117 : POW(aa2)
  & aa118 : POW(aa2 * INTEGER)
  & aa119 : POW(aa2 * INTEGER)
  & aa120 : POW(aa2 * INTEGER)
  & aa121 : POW(aa3 * INTEGER)
  & aa122 : POW(aa3 * INTEGER)
  & aa123 : POW(aa3 * INTEGER)
  & aa124 : POW(aa3 * INTEGER)
  & aa125 : POW(aa3 * INTEGER)
  & aa126 : POW(aa3)
  & aa127 : POW(aa3)
  & aa128 : POW(aa3)
  & aa129 : POW(aa4 * INTEGER)
  & aa130 : POW((aa4 * INTEGER) * INTEGER)
  & aa131 : POW(aa4)
  & aa132 : POW(aa5)
  & aa133 : POW((aa5 * INTEGER) * INTEGER)
  & aa134 : POW(aa5 * INTEGER)
  & aa135 : POW(aa5 * INTEGER)
  & aa136 : POW(aa5 * INTEGER)
  & aa137 : INTEGER
  & aa138 : POW(INTEGER * INTEGER)
  & aa139 : POW(INTEGER * aa7)
  & aa140 : INTEGER
  & aa141 : INTEGER
  & aa142 : INTEGER
  & aa143 : aa6
  & aa144 : INTEGER
  & aa145 : POW(aa6 * INTEGER)
  & aa146 : POW(aa6 * INTEGER)
  & aa147 : POW(aa6 * INTEGER)
  & aa148 : POW(aa6)
  & aa149 : POW((aa7 * INTEGER) * INTEGER)
  & aa150 : POW(aa7 * INTEGER)
  & aa151 : POW(aa7 * INTEGER)
  & aa152 : POW(aa7)
  & aa153 : POW(aa7 * INTEGER)
  & aa154 : INTEGER
  & aa155 : INTEGER
  & aa156 : INTEGER
  & aa157 : POW(aa8)
  & aa158 : POW((aa8 * INTEGER) * INTEGER)
  & aa159 : POW(aa8 * INTEGER)
  & aa160 : POW(aa8)
  & aa161 : POW(aa8 * INTEGER)
  & aa162 : INTEGER
  & aa163 : POW(INTEGER * aa5)
  & aa164 : INTEGER
  & aa165 : INTEGER
  & aa166 : INTEGER
  & aa167 : INTEGER
  & aa168 : INTEGER
  & aa169 : POW(INTEGER * aa9)
  & aa170 : POW(aa9)
  & aa171 : POW(aa9 * aa2)
  & aa172 : POW(aa9 * INTEGER)
  & aa173 : POW(aa9 * INTEGER)
  & aa174 : POW(aa9 * aa2)
  & aa175 : POW(aa9 * INTEGER)
  & aa176 : POW(aa9 * INTEGER)
  & aa177 : POW(aa9 * aa3)
  & aa178 : POW(aa9 * INTEGER)
  & aa179 : POW(aa9 * aa3)
  & aa180 : POW(aa9 * INTEGER)
  & aa181 : POW(aa9 * aa2)
  & aa182 : POW(aa9 * INTEGER)
  & aa183 : POW(aa9 * INTEGER)
  & aa184 : POW(aa9 * INTEGER)
  & aa185 : POW(aa9 * INTEGER)
  & aa186 : POW(aa9 * aa2)
  & aa187 : POW(aa9)
  & aa188 : POW(aa9)
  & aa189 : POW(aa9)
  & aa190 : POW(aa9)
  & aa191 : POW(aa9)
  & aa192 : POW(aa9)
  & aa193 : POW(INTEGER * aa10)
  & aa194 : POW(INTEGER * aa15)
  & aa195 : POW(INTEGER * aa4)
  & aa196 : INTEGER
  & aa197 : INTEGER
  & aa198 : INTEGER
  & aa199 : POW(aa10 * INTEGER)
  & aa200 : POW(aa10 * INTEGER)
  & aa201 : POW(aa10 * INTEGER)
  & aa0 : POW(aa10)
  & aa202 : POW(aa10 * aa2)
  & aa203 : POW(aa10 * INTEGER)
  & aa204 : POW(aa10 * INTEGER)
  & aa205 : POW((aa10 * INTEGER) * aa11)
  & aa206 : POW(aa10 * INTEGER)
  & aa207 : POW(aa10 * INTEGER)
  & aa208 : POW((aa10 * INTEGER) * INTEGER)
  & aa209 : POW(aa10 * INTEGER)
  & aa210 : POW(aa10 * INTEGER)
  & aa211 : POW((aa10 * INTEGER) * INTEGER)
  & aa212 : POW(aa10 * INTEGER)
  & aa213 : POW(aa13)
  & aa214 : POW(aa10 * aa2)
  & aa215 : POW(aa11 * INTEGER)
  & aa216 : POW((aa11 * INTEGER) * INTEGER)
  & aa217 : POW(aa11 * aa2)
  & aa218 : POW((aa12 * INTEGER) * INTEGER)
  & aa219 : POW(aa12 * INTEGER)
  & aa220 : POW((aa13 * INTEGER) * INTEGER)
  & aa221 : POW(aa13 * INTEGER)
  & aa222 : POW(aa13 * INTEGER)
  & aa223 : POW((aa13 * INTEGER) * INTEGER)
  & aa224 : POW(aa13 * INTEGER)
  & aa225 : POW((aa13 * INTEGER) * aa2)
  & aa226 : POW(aa13 * INTEGER)
  & aa227 : POW((aa13 * INTEGER) * aa14)
  & aa228 : POW(aa14 * INTEGER)
  & aa229 : POW(aa14 * INTEGER)
  & aa230 : POW(aa14 * INTEGER)
  & aa231 : POW(aa15 * INTEGER)
  & aa232 : POW(aa15 * INTEGER)
  & aa233 : POW(aa15 * INTEGER)
  & aa234 : POW(aa15)
  & aa235 : POW(aa15 * aa12)
  & aa236 : POW(aa15 * aa2)
  & aa237 : POW((aa15 * INTEGER) * aa2)
  & aa1 : aa10
  & aa238 : POW(INTEGER * aa16)
  & aa239 : INTEGER
  & aa240 : POW(INTEGER * aa17)
  & aa241 : INTEGER
  & aa242 : INTEGER
  & aa243 : POW(aa16)
  & aa244 : POW(aa16 * INTEGER)
  & aa245 : POW(aa16 * INTEGER)
  & aa246 : POW(aa16 * INTEGER)
  & aa247 : POW(aa16 * INTEGER)
  & aa248 : POW(aa16 * INTEGER)
  & aa249 : POW(aa16 * INTEGER)
  & aa250 : POW((aa17 * INTEGER) * INTEGER)
  & aa251 : POW(aa17 * INTEGER)
  & aa252 : POW(aa17 * aa18)
  & aa253 : POW(aa17 * INTEGER)
  & aa254 : POW(aa17)
  & aa255 : POW(aa18 * INTEGER)
  & aa256 : POW(aa18 * INTEGER)
  & aa257 : POW(aa18 * INTEGER)
  & aa258 : POW(aa18 * INTEGER)
  & aa259 : POW(aa18 * INTEGER)
  & aa260 : POW(aa18 * INTEGER)
  & aa261 : POW(aa18)
  & aa262 : POW(aa18)
  & aa263 : POW(aa18)
  & aa264 : POW(aa18 * INTEGER)
  & aa265 : POW(aa18 * INTEGER)
  & aa266 : POW(aa18 * INTEGER)
  & aa267 : POW(aa18 * INTEGER)
  & aa268 : POW(aa16 * INTEGER)
  & aa269 : POW(INTEGER * aa19)
  & aa270 : INTEGER
  & aa271 : INTEGER
  & aa272 : INTEGER
  & aa273 : INTEGER
  & aa274 : POW(INTEGER * INTEGER)
  & aa275 : INTEGER
  & aa276 : INTEGER
  & aa277 : INTEGER
  & aa278 : POW(aa19)
  & aa279 : POW(aa19 * INTEGER)
  & aa280 : POW(aa19 * INTEGER)
  & aa281 : POW((aa19 * INTEGER) * INTEGER)
  & aa282 : INTEGER
  & aa283 : INTEGER
  & aa284 : POW(INTEGER * INTEGER)
  & aa285 : POW(INTEGER * INTEGER)
  & aa286 : INTEGER
  & aa287 : INTEGER
  & aa288 : INTEGER
  & aa289 : POW(INTEGER * aa20)
  & aa290 : INTEGER
  & aa291 : INTEGER
  & aa292 : POW(aa20)
  & aa293 : POW(aa20 * INTEGER)
  & aa294 : POW(aa20 * INTEGER)
  & aa295 : POW((aa20 * INTEGER) * INTEGER)
  & aa296 : POW(aa20 * INTEGER)
  & aa297 : POW((aa20 * INTEGER) * INTEGER)
  & aa298 : INTEGER
  & aa299 : POW(INTEGER * aa21)
  & aa300 : INTEGER
  & aa301 : INTEGER
  & aa302 : POW(aa4)
  & aa303 : POW(aa21)
  & aa304 : POW(aa21 * INTEGER)
  & aa305 : POW(aa21 * INTEGER)
  & aa306 : POW((aa21 * INTEGER) * aa22)
  & aa307 : POW(aa21 * INTEGER)
  & aa308 : POW((aa21 * INTEGER) * aa2)
  & aa309 : POW(aa21 * INTEGER)
  & aa310 : POW((aa21 * INTEGER) * aa25)
  & aa311 : POW(aa21 * aa2)
  & aa312 : POW(aa21 * INTEGER)
  & aa313 : POW(aa22 * INTEGER)
  & aa314 : POW(aa22 * aa23)
  & aa315 : POW(aa22 * INTEGER)
  & aa316 : POW(aa22 * aa24)
  & aa317 : POW(aa22)
  & aa318 : POW(aa23)
  & aa319 : POW(aa23)
  & aa320 : POW(aa23)
  & aa321 : POW(aa23 * aa2)
  & aa322 : POW(aa23 * INTEGER)
  & aa323 : POW(aa23 * aa3)
  & aa324 : POW(aa24 * INTEGER)
  & aa325 : POW(aa24 * INTEGER)
  & aa326 : POW(aa24)
  & aa327 : POW(aa24)
  & aa328 : POW(aa24)
  & aa329 : POW(aa25 * INTEGER)
  & aa330 : POW(aa25 * INTEGER)
  & aa331 : POW(aa25 * INTEGER)
  & aa332 : POW(aa25 * INTEGER)
  & aa333 : POW(aa25 * INTEGER)
  & aa334 : POW(aa25 * INTEGER)
  & aa335 : POW(aa25 * INTEGER)
  & aa336 : POW(aa25)
  & aa57 = 0
  & aa66 = 1
  & aa58 = 2
  & aa62 = 4
  & aa72 = 8
  & aa32 = 16
  & aa33 = 64
  & aa26 = 128
  & aa70 = 9
  & aa60 = 10
  & aa64 = 12
  & aa68 = 17
  & aa59 = 18
  & aa63 = 20
  & aa73 = 24
  & aa69 = 65
  & aa67 = 129
  & aa71 = 25
  & aa61 = 26
  & aa65 = 28
  & aa37 = 0
  & aa49 = 1
  & aa38 = 2
  & aa43 = 4
  & aa55 = 8
  & aa35 = 16
  & aa34 = 64
  & aa36 = 128
  & aa53 = 9
  & aa41 = 10
  & aa47 = 12
  & aa51 = 17
  & aa39 = 18
  & aa45 = 20
  & aa56 = 24
  & aa50 = 65
  & aa44 = 68
  & aa52 = 129
  & aa40 = 130
  & aa46 = 132
  & aa54 = 25
  & aa42 = 26
  & aa48 = 28
  & aa28 = 2
  & aa30 = 4
  & aa27 = 8
  & aa29 = 10
  & aa31 = 12
  & aa81 = 1
  & aa79 = 2
  & aa74 = 3
  & aa82 = 4
  & aa76 = 5
  & aa75 = 6
  & aa83 = 7
  & aa85 = 8
  & aa84 = 9
  & aa80 = 10
  & aa78 = 11
  & aa77 = 12
  & aa86 = 32767
  & aa103 = 42
  & aa87 = 1
  & aa88 = 2
  & aa92 = 3
  & aa91 = 4
  & aa89 = 5
  & aa90 = 6
  & aa104 = 0 .. 255
  & aa108 = 1 .. 256 + 255 * 256
  & aa105 = {4}
  & aa107 = {8}
  & aa106 = {12}
  & aa93 = {aa57,aa66,aa32,aa33,aa26,aa68,aa69,aa67}
  & aa100 = {aa66,aa68,aa69,aa67}
  & aa96 = {aa33,aa69}
  & aa94 = {aa57,aa66,aa58,aa62,aa72,aa32,aa70,aa60,aa64,aa68,aa59,aa63,aa73,aa71,aa61,aa65}
  & aa101 = {aa66,aa62,aa32,aa70,aa64,aa68,aa63,aa71,aa65}
  & aa102 = {aa72,aa70,aa60,aa64,aa71,aa61,aa65}
  & aa99 = {aa57,aa33,aa32,aa26}
  & aa95 = {aa58,aa72,aa60,aa59,aa61}
  & aa98 = {aa38,aa55,aa41,aa39,aa42,aa36,aa40}
  & aa97 = {aa37,aa49,aa38,aa43,aa55,aa35,aa53,aa41,aa47,aa51,aa39,aa45,aa56,aa54,aa42,aa48,aa34,aa50,aa36,aa52,aa40,aa46}
  & aa112 = 0 .. 255
  & aa113 = 0 .. 65535
  & aa114 = 0 .. 4294967295
  & aa111 = 0 .. 127
  & aa109 = 0 .. 1
  & aa110 = 0 .. 32767
  & (aa2 = aa117\/aa116 & aa117/\aa116 = {})
  & aa119 : aa116 +-> aa112
  & aa118 : aa116 +-> aa112
  & aa120 : aa117 +-> aa113
  & aa122 : aa126 +-> aa112
  & aa121 : aa126 +-> aa112
  & aa123 : aa126 +-> aa112
  & aa125 : aa127 +-> aa112
  & aa124 : aa127 +-> aa113
  & (aa3 = aa127\/aa126 & aa127/\aa126 = {})
  & aa129 : aa131 <-> aa112
  & aa130 : aa129 +-> aa112
  & aa136 : aa132 +-> aa112
  & aa135 : aa132 +-> aa112
  & aa134 : aa132 <-> aa112
  & aa133 : aa134 +-> aa112
  & aa144 : aa112
  & aa142 : aa113
  & aa138 : 0 .. 11 +-> aa113
  & aa143 : aa148
  & aa141 : aa112
  & aa137 : aa112
  & aa140 : aa112
  & aa139 : aa112 +-> aa152
  & aa147 : aa148 +-> aa113
  & aa145 : aa148 +-> aa113
  & aa146 : aa148 +-> aa113
  & aa151 : aa152 +-> aa112
  & aa153 : aa152 +-> aa113
  & aa150 : aa152 <-> aa112
  & aa149 : aa150 +-> aa112
  & aa156 : aa112
  & aa155 : aa113
  & aa154 : aa112
  & aa157 <: aa160
  & aa159 : aa160 <-> aa112
  & aa158 : aa159 +-> aa112
  & aa161 : aa160 +-> aa113
  & aa165 : aa112
  & aa164 : aa113
  & aa162 : aa112
  & aa163 : 0 .. aa162 +-> aa132
  & aa168 : aa112
  & aa167 : aa113
  & aa166 : aa113
  & aa169 : aa113 +-> aa170
  & aa173 : aa187 +-> aa112
  & aa171 : aa187 +-> aa115
  & aa172 : aa187 +-> aa112
  & ran(aa173) = {aa87}
  & dom(aa173) = dom(aa171)
  & dom(aa172) = dom(aa171)
  & aa175 : aa188 +-> aa112
  & aa174 : aa188 +-> aa115
  & aa176 : aa188 +-> aa112
  & ran(aa175) = {aa88}
  & dom(aa175) = dom(aa174)
  & dom(aa175) = dom(aa176)
  & aa178 : aa189 +-> aa112
  & aa177 : aa189 +-> aa128
  & ran(aa178) = {aa89}
  & dom(aa178) = dom(aa177)
  & aa180 : aa189 +-> aa112
  & aa179 : aa189 +-> aa128
  & ran(aa180) = {aa90}
  & dom(aa180) = dom(aa179)
  & aa182 : aa191 +-> aa112
  & aa181 : aa191 +-> aa115
  & aa183 : aa191 +-> aa112
  & ran(aa182) = {aa91}
  & dom(aa182) = dom(aa181)
  & dom(aa182) = dom(aa183)
  & aa184 : aa192 +-> aa112
  & aa186 : aa192 +-> aa115
  & aa185 : aa192 +-> aa112
  & ran(aa184) = {aa92}
  & dom(aa184) = dom(aa186)
  & dom(aa184) = dom(aa185)
  & (aa9 = aa187\/aa188\/aa189\/aa190\/aa191\/aa192 & aa187/\aa188 = {} & aa187/\aa189 = {} & aa187/\aa190 = {} & aa187/\aa191 = {} & aa187/\aa192 = {} & aa188/\aa189 = {} & aa188/\aa190 = {} & aa188/\aa191 = {} & aa188/\aa192 = {} & aa189/\aa190 = {} & aa189/\aa191 = {} & aa189/\aa192 = {} & aa190/\aa191 = {} & aa190/\aa192 = {} & aa191/\aa192 = {})
  & aa168 = aa76
  & aa198 : aa112
  & aa197 : aa113
  & aa196 : aa113
  & aa195 : aa113 +-> aa131
  & aa194 : aa104 +-> aa234
  & aa193 : aa104 +-> aa0
  & aa199 : aa0 +-> aa112
  & aa200 : aa0 +-> aa111
  & aa201 : aa0 +-> aa111
  & aa214 : aa0 +-> aa115
  & aa203 : aa0 +-> aa112
  & aa204 : aa0 +-> aa112
  & aa212 : aa0 +-> aa112
  & aa209 : aa0 +-> aa112
  & aa210 : aa0 <-> aa112
  & aa206 : aa0 +-> aa112
  & aa207 : aa0 <-> aa112
  & aa211 : aa210 +-> aa113
  & aa208 : aa207 +-> aa113
  & aa205 : aa201 +-> aa11
  & aa202 : aa0 +-> aa117
  & dom(aa200) = dom(aa202)
  & dom(aa201) <: dom(aa202)
  & dom(aa214) <: dom(aa202)
  & dom(aa202) = dom(aa209)
  & dom(aa202) = dom(aa210)
  & dom(aa202) = dom(aa206)
  & dom(aa202) = dom(aa207)
  & dom(aa200) = dom(aa203)
  & dom(aa200) = dom(aa204)
  & dom(aa200) = dom(aa212)
  & !(aa337).(aa337 : aa2 & aa337 : ran(aa202) => aa337 : aa117 & aa337 : dom(aa120))
  & aa217 : aa11 +-> aa115
  & aa215 : aa11 <-> aa112
  & aa216 : aa215 +-> aa112
  & aa219 : aa12 <-> aa112
  & aa218 : aa219 +-> aa112
  & aa222 : aa13 <-> aa112
  & aa227 : aa222 +-> aa14
  & aa224 : aa13 <-> aa112
  & aa223 : aa224 +-> aa112
  & aa221 : aa13 <-> aa112
  & aa220 : aa221 +-> aa112
  & aa226 : aa13 <-> aa112
  & aa225 : aa226 +-> aa115
  & aa228 : aa14 +-> aa113
  & aa229 : aa14 +-> aa113
  & aa230 : aa14 +-> aa112
  & aa231 : aa234 +-> aa112
  & aa232 : aa234 +-> aa111
  & aa233 : aa234 <-> aa111
  & aa237 : aa233 +-> aa115
  & aa235 : aa234 <-> aa12
  & aa236 : aa234 +-> aa117
  & dom(aa236) = dom(aa231)
  & dom(aa233) = dom(aa231)
  & dom(aa235) = dom(aa231)
  & !(aa337).(aa337 : aa2 & aa337 : ran(aa236) => aa337 : aa117 & aa337 : dom(aa120))
  & aa0 = {aa1}
  & aa1 |-> 0 : aa210
  & aa1 |-> 1 : aa210
  & aa1 |-> 2 : aa210
  & aa1 |-> 3 : aa210
  & aa1 |-> 4 : aa210
  & (aa1 |-> 0) |-> 50 : aa211
  & (aa1 |-> 1) |-> 1 : aa211
  & (aa1 |-> 2) |-> 4 : aa211
  & (aa1 |-> 3) |-> 53 : aa211
  & (aa1 |-> 4) |-> 56 : aa211
  & aa242 : aa112
  & aa241 : aa113
  & aa239 : aa112
  & aa238 : aa112 +-> aa243
  & aa240 : aa108 +-> aa254
  & ran(aa238) = dom(aa249)
  & aa249 : aa243 +-> aa113
  & aa244 : aa243 +-> aa113
  & aa246 : aa243 +-> aa109
  & aa245 : aa243 +-> aa113
  & aa248 : aa243 +-> aa113
  & aa247 : aa243 +-> aa113
  & dom(aa249) = dom(aa244)
  & dom(aa249) = dom(aa246)
  & dom(aa249) = dom(aa245)
  & dom(aa249) = dom(aa248)
  & dom(aa249) = dom(aa247)
  & !(aa338).(aa338 : INTEGER & aa338 : ran(aa245) => aa338 < 32767)
  & aa252 : aa254 +-> aa261
  & aa251 : aa254 <-> aa113
  & aa250 : aa251 +-> aa112
  & aa253 : aa254 +-> aa113
  & aa255 : aa262 +-> aa112
  & aa256 : aa262 +-> aa111
  & aa260 : aa262 +-> aa111
  & aa258 : aa262 +-> aa112
  & aa259 : aa262 +-> aa112
  & aa257 : aa262 +-> aa112
  & (aa18 = aa263\/aa262 & aa263/\aa262 = {})
  & aa264 : aa263 +-> aa111
  & aa266 : aa263 +-> aa111
  & aa267 : aa263 +-> aa111
  & aa265 : aa263 +-> aa111
  & aa242 = aa83
  & ran(aa256) : {aa107,aa106}
  & ran(aa260) <: {0}
  & ran(aa264) = aa105
  & !(aa339).(aa339 : aa16 & aa339 : dom(aa249) => aa249(aa339) : ran(aa250))
  & !(aa339).(aa339 : aa16 & aa339 : dom(aa249) => #(aa340).(aa340 : aa17 & (aa340 : dom(aa251) & (aa249(aa339) : aa250[{aa340} <| aa251] & aa249(aa339) + aa245(aa339) : aa250[{aa340} <| aa251]))))
  & aa268 = {aa341,aa342|(aa341 : aa16 & aa342 : INTEGER) & aa342 |-> aa341 : aa238}
  & !(aa343,aa344).((aa343 : aa16 & aa344 : aa16) & (aa343 : dom(aa249) & (aa344 : dom(aa249) & (aa268(aa343) < aa268(aa344) & aa246(aa343) = 1)))
   =>
    aa249(aa343) .. aa249(aa343) + aa245(aa343) /\ aa249(aa344) .. aa249(aa344) + aa245(aa344) = {})
  & ran(aa248) <: ran(aa251)
  & !(aa345,aa346).((aa345 : aa17 & aa346 : aa17) & (aa345 : dom(aa251) & aa346 : dom(aa251)) => ({aa345} <| aa251) /\ ({aa346} <| aa251) = {})
  & !(aa347,aa348).((aa347 : INTEGER & aa348 : INTEGER) & (aa347 : ran(aa251) & aa348 : ran(aa250)) => aa347 /= aa348)
  & !(aa340).(aa340 : aa17 & aa340 : dom(aa251) => card(ran({aa340} <| aa251)) <= 32767)
  & !(aa347,aa348).((aa347 : INTEGER & aa348 : INTEGER) & (aa347 : ran(aa251) & aa348 : ran(aa251)) => aa347 /= aa348)
  & aa277 : aa112
  & aa276 : aa113
  & aa272 : aa113
  & aa275 : aa113
  & aa270 : aa113
  & aa269 : aa113 +-> aa278
  & aa271 : aa113
  & aa273 : aa113
  & aa274 : aa113 +-> aa112
  & aa280 : aa278 +-> aa112
  & aa279 : aa278 <-> aa113
  & aa281 : aa279 +-> aa112
  & aa287 : aa112
  & aa286 : aa113
  & aa283 : aa113
  & aa285 : aa113 +-> aa112
  & aa282 : aa113
  & aa284 : aa113 +-> aa112
  & aa291 : aa112
  & aa290 : aa113
  & aa288 : aa112
  & aa289 : aa112 +-> aa292
  & aa293 : aa292 +-> aa113
  & aa294 : aa292 <-> aa112
  & aa296 : aa292 <-> aa112
  & aa295 : aa294 +-> aa113
  & aa297 : aa296 +-> aa113
  & aa301 : aa112
  & aa300 : aa113
  & aa298 : aa112
  & aa299 : aa112 +-> aa303
  & aa302 <: aa131
  & aa312 : aa303 +-> aa112
  & aa304 : aa303 +-> aa112
  & aa311 : aa303 +-> aa115
  & aa307 : aa303 <-> aa112
  & aa305 : aa303 <-> aa113
  & aa309 : aa303 <-> aa113
  & aa308 : aa307 +-> aa115
  & aa306 : aa305 +-> aa317
  & aa310 : aa309 +-> aa336
  & dom(aa312) = dom(aa304)
  & dom(aa312) = dom(aa311)
  & dom(aa307) <: dom(aa312)
  & dom(aa305) <: dom(aa312)
  & dom(aa309) <: dom(aa312)
  & aa315 : aa317 +-> aa112
  & aa313 : aa317 +-> aa112
  & aa314 : aa317 +-> aa318
  & aa316 : aa317 +-> aa326
  & dom(aa315) = dom(aa313)
  & dom(aa315) = dom(aa314)
  & dom(aa315) = dom(aa316)
  & (aa23 = aa320\/aa319 & aa320/\aa319 = {})
  & aa321 : aa319 +-> aa115
  & aa322 : aa319 +-> aa112
  & aa323 : aa320 +-> aa128
  & aa324 : aa327 +-> aa113
  & !(aa326).(aa326 : aa24 & aa326 : dom(aa324) => aa324(aa326) mod 32728 = 0)
  & aa325 : aa328 +-> aa113
  & !(aa326).(aa326 : aa24 & aa326 : dom(aa325) => aa325(aa326) mod 32728 /= 0)
  & (aa24 = aa327\/aa328 & aa327/\aa328 = {})
  & aa334 : aa336 +-> aa112
  & aa329 : aa336 +-> aa112
  & aa333 : aa336 +-> aa113
  & aa335 : aa336 +-> aa113
  & aa330 : aa336 +-> aa113
  & aa331 : aa336 +-> aa113
  & aa332 : aa336 +-> aa113
  & dom(aa334) = dom(aa329)
  & dom(aa334) = dom(aa333)
  & dom(aa334) = dom(aa335)
  & dom(aa334) = dom(aa330)
  & dom(aa334) = dom(aa331)
  & dom(aa334) = dom(aa332)
INITIALISATION
    skip
END
