/* Variables */
   nationality = {(1|->"norwegian"),(2|->"dane"),(3|->"brit"),(4|->"german"),(5|->"swede")}
 & colors = {(1|->"yellow"),(2|->"blue"),(3|->"red"),(4|->"green"),(5|->"white")}
 & pets = {(1|->"cat"),(2|->"horse"),(3|->"bird"),(4|->"fish"),(5|->"dog")}
 & cigars = {(1|->"dh"),(2|->"blend"),(3|->"pm"),(4|->"prince"),(5|->"bm")}
 & drinks = {(1|->"water"),(2|->"tea"),(3|->"mylk"),(4|->"coffee"),(5|->"beer")}
